name: Packages

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

jobs:
  prepare_jobs:
    runs-on: ubuntu-latest
    container: python:3-alpine
    steps:
      - uses: actions/checkout@v4
      - name: Generate build list
        id: set-matrix
        run: |
          build_list=$(./get_depends.py)
          echo "build_list=$build_list" >> $GITHUB_OUTPUT
          echo "Generated build list: $build_list"  # Debug output
    outputs:
      build_list: ${{ steps.set-matrix.outputs.build_list }}

  build:
    needs: [prepare_jobs]
    if: steps.set-matrix.outputs.build_list != ''
    runs-on: ubuntu-latest
    container: ghcr.io/pspdev/pspsdk:latest
    strategy:
      fail-fast: false
      matrix:
        packages: ${{ fromJson(steps.set-matrix.outputs.build_list) }}
